import {
  BookTemplateIcon,
  HomeIcon,
  SettingsIcon,
  TrashIcon,
} from "lucide-react";
import { Theme } from "./types";

export const data = {
  user: {
    name: "Shadcnm",
    email: "m@example.com",
    avatar: "avatar/shadcn.jpg",
  },

  navMain: [
    {
      title: "Home",
      url: "/dashboard",
      icon: HomeIcon,
    },
    { title: "Trash", url: "/trash", icon: TrashIcon },
    {
      title: "Templates",
      url: "/templates",
      icon: BookTemplateIcon,
    },
    { title: "Settings", url: "/settings", icon: SettingsIcon },
  ],
};

export const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    transition: {
      type: "spring",
      stiffness: 100,
    },
  },
};

export const themes: Theme[] = [
  {
    name: "Default",
    fontFamily: "'Inter',sans-serif",
    fontColor: "#000000",
    backgroundColor: "#f0f0f0",
    accentColor: "#3b82f6",
    navbarColor: "#ffffff",
    slideBackgroundColor: "#f0f0f0",
    type: "light",
  },
  {
    name: "Dark Elegance",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#ffffff",
    backgroundColor: "#1a1a1a",
    slideBackgroundColor: "#2c2c2c",
    accentColor: "#ffd700",
    gradientBackground: "linear-gradient(135deg, #2c2c2c 0%, #1a1a1a 100%)",
    navbarColor: "#2c2c2c",
    slidebarColor: "#1a1a1a",
    type: "dark",
  },
  {
    name: "Ocean Breeze",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#0f172a",
    backgroundColor: "#e0f7fa",
    slideBackgroundColor: "#b2ebf2",
    accentColor: "#0288d1",
    gradientBackground: "linear-gradient(135deg, #b2ebf2 0%, #e0f7fa 100%)",
    navbarColor: "#ffffff",
    slidebarColor: "#b2ebf2",
    type: "light",
  },
  {
    name: "Midnight Indigo",
    fontFamily: "'Roboto Slab', serif",
    fontColor: "#e0e7ff",
    backgroundColor: "#1e1b4b",
    slideBackgroundColor: "#312e81",
    accentColor: "#6366f1",
    gradientBackground: "linear-gradient(135deg, #312e81 0%, #1e1b4b 100%)",
    navbarColor: "#312e81",
    slidebarColor: "#1e1b4b",
    type: "dark",
  },
  {
    name: "Sunset Glow",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#2e2e2e",
    backgroundColor: "#fff7ed",
    slideBackgroundColor: "#ffe4c4",
    accentColor: "#f97316",
    gradientBackground: "linear-gradient(135deg, #ffe4c4 0%, #fff7ed 100%)",
    navbarColor: "#ffffff",
    slidebarColor: "#ffe4c4",
    type: "light",
  },
  {
    name: "Cyber Night",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#e0e0e0",
    backgroundColor: "#0a0a0a",
    slideBackgroundColor: "#1a1a1a",
    accentColor: "#00ffff",
    gradientBackground: "linear-gradient(135deg, #1a1a1a 0%, #000000 100%)",
    navbarColor: "#1a1a1a",
    slidebarColor: "#0a0a0a",
    type: "dark",
  },
  {
    name: "Forest Whisper",
    fontFamily: "'Lora', serif",
    fontColor: "#2c3e2f",
    backgroundColor: "#ecf4ee",
    slideBackgroundColor: "#d8e9db",
    accentColor: "#2e7d32",
    gradientBackground: "linear-gradient(135deg, #d8e9db 0%, #ecf4ee 100%)",
    navbarColor: "#ffffff",
    slidebarColor: "#d8e9db",
    type: "light",
  },
  {
    name: "Crimson Night",
    fontFamily: "'Merriweather', serif",
    fontColor: "#fff0f0",
    backgroundColor: "#2b0000",
    slideBackgroundColor: "#3c0000",
    accentColor: "#ff4d4d",
    gradientBackground: "linear-gradient(135deg, #3c0000 0%, #2b0000 100%)",
    navbarColor: "#3c0000",
    slidebarColor: "#2b0000",
    type: "dark",
  },
  {
    name: "Lavender Mist",
    fontFamily: "'Quicksand', sans-serif",
    fontColor: "#1f1f1f",
    backgroundColor: "#f3e8ff",
    slideBackgroundColor: "#e9d5ff",
    accentColor: "#a855f7",
    gradientBackground: "linear-gradient(135deg, #e9d5ff 0%, #f3e8ff 100%)",
    navbarColor: "#ffffff",
    slidebarColor: "#e9d5ff",
    type: "light",
  },
  {
    name: "Graphite Steel",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#e5e5e5",
    backgroundColor: "#202124",
    slideBackgroundColor: "#2d2f33",
    accentColor: "#5f6368",
    gradientBackground: "linear-gradient(135deg, #2d2f33 0%, #202124 100%)",
    navbarColor: "#2d2f33",
    slidebarColor: "#202124",
    type: "dark",
  },
  {
    name: "Peach Cream",
    fontFamily: "'Josefin Sans', sans-serif",
    fontColor: "#3c2f2f",
    backgroundColor: "#fff0e1",
    slideBackgroundColor: "#ffe1c6",
    accentColor: "#ff8a65",
    gradientBackground: "linear-gradient(135deg, #ffe1c6 0%, #fff0e1 100%)",
    navbarColor: "#ffffff",
    slidebarColor: "#ffe1c6",
    type: "light",
  },
  {
    name: "Emerald Abyss",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#d1fae5",
    backgroundColor: "#052e16",
    slideBackgroundColor: "#064e3b",
    accentColor: "#10b981",
    gradientBackground: "linear-gradient(135deg, #064e3b 0%, #052e16 100%)",
    navbarColor: "#064e3b",
    slidebarColor: "#052e16",
    type: "dark",
  },
];
