import {
  BookTemplateIcon,
  HomeIcon,
  SettingsIcon,
  TrashIcon,
} from "lucide-react";
import { ContentItem, ContentType, Slide, Theme } from "./types";
import { v4 as uuidv4 } from "uuid";

export const data = {
  user: {
    name: "Shadcnm",
    email: "m@example.com",
    avatar: "avatar/shadcn.jpg",
  },

  navMain: [
    {
      title: "Home",
      url: "/dashboard",
      icon: HomeIcon,
    },
    { title: "Trash", url: "/trash", icon: TrashIcon },
    {
      title: "Templates",
      url: "/templates",
      icon: BookTemplateIcon,
    },
    { title: "Settings", url: "/settings", icon: SettingsIcon },
  ],
};

export const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const itemVariants = {
  hidden: {
    opacity: 0,
  },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const themes: Theme[] = [
  {
    name: "Default",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#000000",
    backgroundColor: "#f0f0f0",
    accentColor: "#3b82f6",
    navbarColor: "#ffffff",
    slideBackgroundColor: "#f0f0f0",
    type: "light",
  },
  {
    name: "Dark Elegance",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#ffffff",
    backgroundColor: "#121212",
    slideBackgroundColor: "#2a2a2a",
    accentColor: "#ffd700",
    gradientBackground: "linear-gradient(135deg, #2a2a2a 0%, #121212 100%)",
    navbarColor: "#2a2a2a",
    sidebarColor: "#121212",
    type: "dark",
  },
  {
    name: "Aurora Drift",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#e0f2fe",
    backgroundColor: "#0f172a",
    slideBackgroundColor: "#1e3a8a",
    accentColor: "#38bdf8",
    gradientBackground:
      "linear-gradient(135deg, #0f172a 0%, #1e3a8a 35%, #38bdf8 100%)",
    navbarColor: "#1e3a8a",
    sidebarColor: "#0f172a",
    type: "dark",
  },
  {
    name: "Solar Dawn",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#1a1a1a",
    backgroundColor: "#fff7e6",
    slideBackgroundColor: "#ffe0b2",
    accentColor: "#f59e0b",
    gradientBackground:
      "linear-gradient(135deg, #fff7e6 0%, #ffedd5 40%, #fbbf24 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#ffedd5",
    type: "light",
  },
  {
    name: "Cyber Aurora",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#e0e0e0",
    backgroundColor: "#000000",
    slideBackgroundColor: "#111827",
    accentColor: "#22d3ee",
    gradientBackground:
      "linear-gradient(135deg, #000000 0%, #1e293b 50%, #22d3ee 100%)",
    navbarColor: "#111827",
    sidebarColor: "#000000",
    type: "dark",
  },
  {
    name: "Velvet Sunset",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#2e2e2e",
    backgroundColor: "#fff5f7",
    slideBackgroundColor: "#ffe4e6",
    accentColor: "#fb7185",
    gradientBackground:
      "linear-gradient(135deg, #ffe4e6 0%, #fecdd3 40%, #fda4af 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#ffe4e6",
    type: "light",
  },
  {
    name: "Galactic Violet",
    fontFamily: "'DM Sans', sans-serif",
    fontColor: "#e5e7eb",
    backgroundColor: "#1e1b4b",
    slideBackgroundColor: "#312e81",
    accentColor: "#a855f7",
    gradientBackground:
      "linear-gradient(135deg, #312e81 0%, #4c1d95 50%, #7e22ce 100%)",
    navbarColor: "#312e81",
    sidebarColor: "#1e1b4b",
    type: "dark",
  },
  {
    name: "Mint Horizon",
    fontFamily: "'Manrope', sans-serif",
    fontColor: "#1e293b",
    backgroundColor: "#d1fae5",
    slideBackgroundColor: "#a7f3d0",
    accentColor: "#10b981",
    gradientBackground:
      "linear-gradient(135deg, #d1fae5 0%, #6ee7b7 40%, #10b981 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#a7f3d0",
    type: "light",
  },
  {
    name: "Obsidian Flame",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#f5f5f5",
    backgroundColor: "#1a1a1a",
    slideBackgroundColor: "#2d0000",
    accentColor: "#ef4444",
    gradientBackground:
      "linear-gradient(135deg, #000000 0%, #2d0000 40%, #7f1d1d 100%)",
    navbarColor: "#2d0000",
    sidebarColor: "#1a1a1a",
    type: "dark",
  },
  {
    name: "Iridescent Sky",
    fontFamily: "'Urbanist', sans-serif",
    fontColor: "#1f2937",
    backgroundColor: "#e0f2fe",
    slideBackgroundColor: "#bae6fd",
    accentColor: "#6366f1",
    gradientBackground:
      "linear-gradient(135deg, #bae6fd 0%, #c7d2fe 50%, #fbcfe8 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#bae6fd",
    type: "light",
  },
  {
    name: "Ocean Breeze",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#0f172a",
    backgroundColor: "#e0f7fa",
    slideBackgroundColor: "#b2ebf2",
    accentColor: "#0288d1",
    gradientBackground: "linear-gradient(135deg, #b2ebf2 0%, #e0f7fa 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#b2ebf2",
    type: "light",
  },
  {
    name: "Midnight Indigo",
    fontFamily: "'Roboto Slab', serif",
    fontColor: "#e0e7ff",
    backgroundColor: "#1e1b4b",
    slideBackgroundColor: "#312e81",
    accentColor: "#6366f1",
    gradientBackground: "linear-gradient(135deg, #312e81 0%, #1e1b4b 100%)",
    navbarColor: "#312e81",
    sidebarColor: "#1e1b4b",
    type: "dark",
  },
  {
    name: "Sunset Glow",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#2e2e2e",
    backgroundColor: "#fff7ed",
    slideBackgroundColor: "#ffe4c4",
    accentColor: "#f97316",
    gradientBackground: "linear-gradient(135deg, #ffe4c4 0%, #fff7ed 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#ffe4c4",
    type: "light",
  },
  {
    name: "Cyber Night",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#e0e0e0",
    backgroundColor: "#0a0a0a",
    slideBackgroundColor: "#1a1a1a",
    accentColor: "#00ffff",
    gradientBackground: "linear-gradient(135deg, #1a1a1a 0%, #000000 100%)",
    navbarColor: "#1a1a1a",
    sidebarColor: "#0a0a0a",
    type: "dark",
  },
  {
    name: "Forest Whisper",
    fontFamily: "'Lora', serif",
    fontColor: "#2c3e2f",
    backgroundColor: "#ecf4ee",
    slideBackgroundColor: "#d8e9db",
    accentColor: "#2e7d32",
    gradientBackground: "linear-gradient(135deg, #d8e9db 0%, #ecf4ee 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#d8e9db",
    type: "light",
  },
  {
    name: "Crimson Night",
    fontFamily: "'Merriweather', serif",
    fontColor: "#fff0f0",
    backgroundColor: "#2b0000",
    slideBackgroundColor: "#3c0000",
    accentColor: "#ff4d4d",
    gradientBackground: "linear-gradient(135deg, #3c0000 0%, #2b0000 100%)",
    navbarColor: "#3c0000",
    sidebarColor: "#2b0000",
    type: "dark",
  },
  {
    name: "Lavender Mist",
    fontFamily: "'Quicksand', sans-serif",
    fontColor: "#1f1f1f",
    backgroundColor: "#f3e8ff",
    slideBackgroundColor: "#e9d5ff",
    accentColor: "#a855f7",
    gradientBackground: "linear-gradient(135deg, #e9d5ff 0%, #f3e8ff 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#e9d5ff",
    type: "light",
  },
  {
    name: "Graphite Steel",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#e5e5e5",
    backgroundColor: "#202124",
    slideBackgroundColor: "#2d2f33",
    accentColor: "#5f6368",
    gradientBackground: "linear-gradient(135deg, #2d2f33 0%, #202124 100%)",
    navbarColor: "#2d2f33",
    sidebarColor: "#202124",
    type: "dark",
  },
  {
    name: "Peach Cream",
    fontFamily: "'Josefin Sans', sans-serif",
    fontColor: "#3c2f2f",
    backgroundColor: "#fff0e1",
    slideBackgroundColor: "#ffe1c6",
    accentColor: "#ff8a65",
    gradientBackground: "linear-gradient(135deg, #ffe1c6 0%, #fff0e1 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#ffe1c6",
    type: "light",
  },
  {
    name: "Emerald Abyss",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#d1fae5",
    backgroundColor: "#052e16",
    slideBackgroundColor: "#064e3b",
    accentColor: "#10b981",
    gradientBackground: "linear-gradient(135deg, #064e3b 0%, #052e16 100%)",
    navbarColor: "#064e3b",
    sidebarColor: "#052e16",
    type: "dark",
  },
  {
    name: "Arctic Frost",
    fontFamily: "'Rubik', sans-serif",
    fontColor: "#0f172a",
    backgroundColor: "#f0faff",
    slideBackgroundColor: "#dbeafe",
    accentColor: "#38bdf8",
    gradientBackground: "linear-gradient(135deg, #dbeafe 0%, #f0faff 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#dbeafe",
    type: "light",
  },
  {
    name: "Golden Noir",
    fontFamily: "'Cormorant Garamond', serif",
    fontColor: "#f5f5dc",
    backgroundColor: "#0d0d0d",
    slideBackgroundColor: "#1c1c1c",
    accentColor: "#ffcc00",
    gradientBackground: "linear-gradient(135deg, #1c1c1c 0%, #0d0d0d 100%)",
    navbarColor: "#1c1c1c",
    sidebarColor: "#0d0d0d",
    type: "dark",
  },
  {
    name: "Coral Reef",
    fontFamily: "'Karla', sans-serif",
    fontColor: "#1e293b",
    backgroundColor: "#fff5f5",
    slideBackgroundColor: "#ffe4e6",
    accentColor: "#fb7185",
    gradientBackground: "linear-gradient(135deg, #ffe4e6 0%, #fff5f5 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#ffe4e6",
    type: "light",
  },
  {
    name: "Obsidian Dream",
    fontFamily: "'DM Sans', sans-serif",
    fontColor: "#e5e7eb",
    backgroundColor: "#0b0b0d",
    slideBackgroundColor: "#18181b",
    accentColor: "#8b5cf6",
    gradientBackground: "linear-gradient(135deg, #18181b 0%, #0b0b0d 100%)",
    navbarColor: "#18181b",
    sidebarColor: "#0b0b0d",
    type: "dark",
  },
  {
    name: "Mint Cloud",
    fontFamily: "'Manrope', sans-serif",
    fontColor: "#1e293b",
    backgroundColor: "#e6fffa",
    slideBackgroundColor: "#b2f5ea",
    accentColor: "#0d9488",
    gradientBackground: "linear-gradient(135deg, #b2f5ea 0%, #e6fffa 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#b2f5ea",
    type: "light",
  },
  {
    name: "Royal Plum",
    fontFamily: "'Merriweather Sans', sans-serif",
    fontColor: "#f3e8ff",
    backgroundColor: "#3b0764",
    slideBackgroundColor: "#581c87",
    accentColor: "#a855f7",
    gradientBackground: "linear-gradient(135deg, #581c87 0%, #3b0764 100%)",
    navbarColor: "#581c87",
    sidebarColor: "#3b0764",
    type: "dark",
  },
  {
    name: "Amber Fields",
    fontFamily: "'Source Sans 3', sans-serif",
    fontColor: "#2e2e2e",
    backgroundColor: "#fff8e1",
    slideBackgroundColor: "#ffecb3",
    accentColor: "#fbbf24",
    gradientBackground: "linear-gradient(135deg, #ffecb3 0%, #fff8e1 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#ffecb3",
    type: "light",
  },
  {
    name: "Neon Pulse",
    fontFamily: "'Share Tech Mono', monospace",
    fontColor: "#e0f2fe",
    backgroundColor: "#020617",
    slideBackgroundColor: "#0f172a",
    accentColor: "#22d3ee",
    gradientBackground: "linear-gradient(135deg, #0f172a 0%, #020617 100%)",
    navbarColor: "#0f172a",
    sidebarColor: "#020617",
    type: "dark",
  },
  {
    name: "Rose Champagne",
    fontFamily: "'Urbanist', sans-serif",
    fontColor: "#3f3f46",
    backgroundColor: "#fff1f2",
    slideBackgroundColor: "#ffe4e6",
    accentColor: "#f472b6",
    gradientBackground: "linear-gradient(135deg, #ffe4e6 0%, #fff1f2 100%)",
    navbarColor: "#ffffff",
    sidebarColor: "#ffe4e6",
    type: "light",
  },
  {
    name: "Titanium Shadow",
    fontFamily: "'IBM Plex Sans', sans-serif",
    fontColor: "#e5e7eb",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#9ca3af",
    gradientBackground: "linear-gradient(135deg, #1e1e1e 0%, #121212 100%)",
    navbarColor: "#1e1e1e",
    sidebarColor: "#121212",
    type: "dark",
  },
];

export const CreatePageCard = [
  {
    title: "Use a",
    highlightedText: "Template",
    description: "Write a prompt and leave everything else for use to handle",
    type: "template",
  },
  {
    title: "Generate with",
    highlightedText: "Creative AI",
    description: "Write a prompt and leave everything else for use to handle",
    type: "creative-ai",
    highligh: true,
  },
  {
    title: "Start from",
    highlightedText: "Scratch",
    description: "Write a prompt and leave everything else for use to handle",
    type: "create-scratch",
  },
];

export type LayoutComponent = {
  type: ContentType;
  content?: string | string[] | { src?: string; alt?: string };
  style?: Record<string, string>;
  children?: LayoutComponent[];
};

export type Layout = {
  id: string;
  name: string;
  description: string;
  layoutType: string;
  components: LayoutComponent[];
};

export const existingLayouts: ContentItem[] = [
  {
    id: uuidv4(),
    type: "container",
    name: "Title Slide",
    content: [
      {
        id: uuidv4(),
        type: "title",
        name: "Title",
        content: "Welcome to the Future of AI",
        style: { textAlign: "center", fontSize: "3rem", fontWeight: "bold" },
      },
      {
        id: uuidv4(),
        type: "paragraph",
        name: "Subtitle",
        content:
          "Exploring innovation, creativity, and intelligence redefined.",
        style: {
          textAlign: "center",
          fontSize: "1.25rem",
          color: "#666",
          marginTop: "1rem",
        },
      },
      {
        id: uuidv4(),
        type: "image",
        name: "Hero Image",
        content: { src: "", alt: "Futuristic neural network visualization" },
        style: { width: "80%", margin: "2rem auto", borderRadius: "12px" },
      },
    ],
  },
  {
    id: uuidv4(),
    type: "container",
    name: "Two Column Comparison",
    content: [
      {
        id: uuidv4(),
        type: "multiColumn",
        name: "Columns",
        content: [
          {
            id: uuidv4(),
            type: "column",
            name: "Left Column",
            content: [
              {
                id: uuidv4(),
                type: "heading2",
                name: "Heading",
                content: "Traditional Systems",
              },
              {
                id: uuidv4(),
                type: "bulletedList",
                name: "List",
                content: [
                  "Rigid infrastructure",
                  "High maintenance costs",
                  "Limited scalability",
                ],
              },
            ],
          },
          {
            id: uuidv4(),
            type: "column",
            name: "Right Column",
            content: [
              {
                id: uuidv4(),
                type: "heading2",
                name: "Heading",
                content: "Modern AI Systems",
              },
              {
                id: uuidv4(),
                type: "bulletedList",
                name: "List",
                content: [
                  "Adaptive and self-learning",
                  "Cloud-based scalability",
                  "Lower operational costs",
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
