import NotFoundIcon from "@/icons/not-found-icon";
import React from "react";

const NotFound = () => {
  return (
    <div className="flex flex-col min-h-[70%] w-full justify-center items-center gap-12">
      <NotFoundIcon />
      <div className="flex flex-col items-center justify-center text-center">
        <p className="text-3xl font-semibold text-primary">
          Nothing to see here
        </p>
        <p className="text-base font-normal text-muted-foreground">
          So here is a random image generated by{" "}
          <span className="text-blue-400 font-bold">Creative AI</span>
        </p>
      </div>
    </div>
  );
};

export default NotFound;
